# GitHub Copilot Setup Steps
# This workflow sets up the development environment for GitHub Copilot coding agents
# Must be named copilot-setup-steps.yml with a copilot-setup-steps job per GitHub docs
name: Copilot Setup Steps

on:
  # This workflow is designed to be called by GitHub Copilot coding agents
  workflow_dispatch:

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    env:
      GCS_BUCKET: ukulele-tuesday-songbooks
      BUYMEACOFFEE_API_TOKEN: ${{ secrets.BUYMEACOFFEE_API_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y mupdf-tools

      - name: Setup uv
        uses: astral-sh/setup-uv@v1

      - name: Install Python dependencies
        run: uv sync
        timeout-minutes: 3

      - name: Verify setup
        run: |
          echo "✅ System dependencies installed"
          echo "✅ uv package manager installed"
          echo "✅ Python dependencies installed"
          echo "✅ Environment variable GCS_BUCKET set to: $GCS_BUCKET"
          echo "✅ Environment variable BUYMEACOFFEE_API_TOKEN set to: <REDACTED>"
          echo "Setup completed successfully!"
